name: Package Release

# https://help.github.com/en/actions/reference/events-that-trigger-workflows
on: # Trigger the workflow on push or pull request for the main branch, tag push, or release published
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main]
  release:
    types: [published]

jobs:
  build:
    uses: ./.github/workflows/_create-pkg.yml
    with:
      python-version: "3.10"
      artifact-name: pypi-packages-${{ github.sha }}

  publish:
    needs: build
    if: startsWith(github.event.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ“¥ Download artifact
        uses: actions/download-artifact@v7
        with:
          name: pypi-packages-${{ github.sha }}
          path: dist
      - name: ðŸ“‹ Show packages
        run: ls -lh dist/

      - name: ðŸš€ Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@v1.13.0
        with:
          password: ${{ secrets.test_pypi_password }}
          repository_url: https://test.pypi.org/legacy/

      - name: ðŸš€ Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@v1.13.0
        with:
          password: ${{ secrets.pypi_password }}

  release-upload:
    needs: build
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: ðŸ“¥ Download artifact
        uses: actions/download-artifact@v7
        with:
          name: pypi-packages-${{ github.sha }}
          path: dist
      - name: ðŸ“‹ Show packages
        run: ls -lh dist/

      - name: ðŸ“¤ Upload to release
        uses: AButler/upload-release-assets@v3.0
        with:
          files: "dist/*"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-id: ${{ github.event.release.id }}
          release-tag: ${{ github.ref_name }}
